// data.js - Shared car data for OBerlo

const cars = [
    {
        id: 'aston-martin-db12',
        name: 'Aston Martin DB12',
        subtitle: 'V8 Twin-Turbo · 671 hp',
        price: '$248,000',
        badge: 'Luxury',
        category: 'luxury',
        year: 2024,
        image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400',
        heroImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800',
        engine: '4.0L Twin-Turbo V8',
        horsepower: '671 hp',
        topSpeed: '202 mph',
        zeroToSixty: '3.5s',
        transmission: '8-Speed Automatic',
        drivetrain: 'RWD',
        description: 'The Aston Martin DB12 combines breathtaking performance with handcrafted luxury, delivering grand touring comfort and exhilarating speed.',
        features: ['24-Month Warranty', 'Premium Leather Interior', 'Adaptive Suspension', 'Free Delivery']
    },
    {
        id: 'bugatti-chiron',
        name: 'Bugatti Chiron',
        subtitle: 'W16 Quad-Turbo · 1479 hp',
        price: '$3,200,000',
        badge: 'Hypercar',
        category: 'hypercar',
        year: 2020,
        image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=400',
        heroImage: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800',
        engine: '8.0L Quad-Turbo W16',
        horsepower: '1479 hp',
        topSpeed: '261 mph',
        zeroToSixty: '2.4s',
        transmission: '7-Speed DSG',
        drivetrain: 'AWD',
        description: 'The Bugatti Chiron is one of the fastest production cars ever built, combining engineering excellence with unmatched luxury.',
        features: ['Factory Warranty', 'Carbon Fiber Package', 'Exclusive Interior', 'Ceramic Brakes']
    },
    {
        id: 'tesla-model-s-plaid',
        name: 'Tesla Model S Plaid',
        subtitle: 'Electric · 1020 hp',
        price: '$109,000',
        badge: 'Electric',
        category: 'electric',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
        heroImage: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
        engine: 'Tri-Motor Electric',
        horsepower: '1020 hp',
        topSpeed: '200 mph',
        zeroToSixty: '1.99s',
        transmission: 'Single-Speed',
        drivetrain: 'AWD',
        description: 'The Tesla Model S Plaid offers incredible electric performance with cutting-edge technology and impressive driving range.',
        features: ['Autopilot', '8-Year Battery Warranty', 'Glass Roof', 'Premium Audio']
    },
    {
        id: 'nissan-gt-r-nismo',
        name: 'Nissan GT-R Nismo',
        subtitle: 'V6 Twin-Turbo · 600 hp',
        price: '$225,000',
        badge: 'NISMO',
        category: 'sports',
        year: 2022,
        image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
        heroImage: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        engine: '3.8L Twin-Turbo V6',
        horsepower: '600 hp',
        topSpeed: '205 mph',
        zeroToSixty: '2.9s',
        transmission: '6-Speed Dual-Clutch',
        drivetrain: 'AWD',
        description: 'Known as Godzilla, the GT-R Nismo delivers race-inspired engineering with remarkable everyday usability.',
        features: ['Track Package', 'Carbon Hood', 'Brembo Brakes', 'Premium Warranty']
    },
    {
        id: 'toyota-supra-gr',
        name: 'Toyota GR Supra',
        subtitle: 'Inline-6 Turbo · 382 hp',
        price: '$58,000',
        badge: 'Sports',
        category: 'sports',
        year: 2024,
        image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=400',
        heroImage: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800',
        engine: '3.0L Turbo Inline-6',
        horsepower: '382 hp',
        topSpeed: '155 mph',
        zeroToSixty: '3.9s',
        transmission: '8-Speed Automatic',
        drivetrain: 'RWD',
        description: 'The Toyota GR Supra delivers agile handling and thrilling turbocharged performance inspired by its racing heritage.',
        features: ['Apple CarPlay', 'Adaptive Cruise Control', 'Sport Differential', 'LED Headlights']
    },
    {
        id: 'ford-mustang-dark-horse',
        name: 'Ford Mustang Dark Horse',
        subtitle: 'V8 · 500 hp',
        price: '$72,000',
        badge: 'Muscle',
        category: 'muscle',
        year: 2024,
        image: 'https://images.unsplash.com/photo-1494905998402-395d579af36f?w=400',
        heroImage: 'https://images.unsplash.com/photo-1494905998402-395d579af36f?w=800',
        engine: '5.0L Coyote V8',
        horsepower: '500 hp',
        topSpeed: '166 mph',
        zeroToSixty: '3.7s',
        transmission: '10-Speed Auto',
        drivetrain: 'RWD',
        description: 'Ford\'s most capable naturally aspirated Mustang combines track-ready engineering with classic V8 excitement.',
        features: ['Launch Control', 'Brembo Brakes', 'Track Mode', 'Performance Exhaust']
    },
    {
        id: 'chevrolet-corvette-z06',
        name: 'Chevrolet Corvette Z06',
        subtitle: 'V8 · 670 hp',
        price: '$125,000',
        badge: 'Supercar',
        category: 'sports',
        year: 2024,
        image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
        heroImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        engine: '5.5L Flat-Plane V8',
        horsepower: '670 hp',
        topSpeed: '195 mph',
        zeroToSixty: '2.6s',
        transmission: '8-Speed DCT',
        drivetrain: 'RWD',
        description: 'The Corvette Z06 features a race-derived flat-plane crank V8 that delivers breathtaking performance.',
        features: ['Magnetic Ride', 'Carbon Aero', 'Performance Data Recorder', 'Competition Seats']
    },
    {
        id: 'lexus-lc500',
        name: 'Lexus LC 500',
        subtitle: 'V8 · 471 hp',
        price: '$102,000',
        badge: 'Luxury',
        category: 'luxury',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=400',
        heroImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800',
        engine: '5.0L V8',
        horsepower: '471 hp',
        topSpeed: '168 mph',
        zeroToSixty: '4.4s',
        transmission: '10-Speed Automatic',
        drivetrain: 'RWD',
        description: 'The Lexus LC 500 blends Japanese craftsmanship with naturally aspirated V8 performance.',
        features: ['Mark Levinson Audio', 'Leather Interior', 'Heads-Up Display', 'Adaptive Suspension']
    },
    {
        id: 'koenigsegg-jesko',
        name: 'Koenigsegg Jesko',
        subtitle: 'V8 Twin-Turbo · 1600 hp',
        price: '$3,000,000',
        badge: 'Hypercar',
        category: 'hypercar',
        year: 2022,
        image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400',
        heroImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        engine: '5.0L Twin-Turbo V8',
        horsepower: '1600 hp',
        topSpeed: '300+ mph',
        zeroToSixty: '2.5s',
        transmission: '9-Speed LST',
        drivetrain: 'RWD',
        description: 'The Jesko is built to redefine speed with groundbreaking aerodynamics and immense power.',
        features: ['Carbon Chassis', 'Active Aero', 'Track Telemetry', 'Custom Interior']
    },
    {
        id: 'rolls-royce-phantom',
        name: 'Rolls-Royce Phantom',
        subtitle: 'V12 · 563 hp',
        price: '$510,000',
        badge: 'Ultra Luxury',
        category: 'luxury',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=400',
        heroImage: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800',
        engine: '6.75L Twin-Turbo V12',
        horsepower: '563 hp',
        topSpeed: '155 mph',
        zeroToSixty: '5.1s',
        transmission: '8-Speed Automatic',
        drivetrain: 'RWD',
        description: 'The Phantom represents the highest level of automotive luxury with unmatched craftsmanship and comfort.',
        features: ['Starlight Headliner', 'Rear Executive Seating', 'Champagne Cooler', 'Bespoke Finish']
    },
    {
        id: 'pagani-huayra',
        name: 'Pagani Huayra',
        subtitle: 'V12 Twin-Turbo · 791 hp',
        price: '$2,800,000',
        badge: 'Hypercar',
        category: 'hypercar',
        year: 2019,
        image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400',
        heroImage: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
        engine: '6.0L Twin-Turbo V12',
        horsepower: '791 hp',
        topSpeed: '238 mph',
        zeroToSixty: '2.8s',
        transmission: '7-Speed Sequential',
        drivetrain: 'RWD',
        description: 'The Pagani Huayra is a masterpiece of engineering featuring handcrafted carbon fiber construction and a handcrafted AMG V12 engine.',
        features: ['Carbon Fiber Body', 'Bespoke Interior', 'Active Aerodynamics', 'Limited Production']
    },
    {
        id: 'dodge-challenger-srt-demon-170',
        name: 'Dodge Challenger SRT Demon 170',
        subtitle: 'Supercharged V8 · 1025 hp',
        price: '$125,000',
        badge: 'Muscle',
        category: 'muscle',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=400',
        heroImage: 'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=800',
        engine: '6.2L Supercharged HEMI V8',
        horsepower: '1025 hp',
        topSpeed: '168 mph',
        zeroToSixty: '1.7s',
        transmission: '8-Speed Automatic',
        drivetrain: 'RWD',
        description: 'The ultimate factory-built drag car with incredible acceleration and legendary HEMI power.',
        features: ['Launch Assist', 'Drag Mode', 'Line Lock', 'Performance Pages']
    },
    {
        id: 'honda-civic-type-r',
        name: 'Honda Civic Type R',
        subtitle: 'Turbo I4 · 315 hp',
        price: '$46,000',
        badge: 'Performance',
        category: 'performance',
        year: 2024,
        image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=400',
        heroImage: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800',
        engine: '2.0L Turbo Inline-4',
        horsepower: '315 hp',
        topSpeed: '169 mph',
        zeroToSixty: '5.0s',
        transmission: '6-Speed Manual',
        drivetrain: 'FWD',
        description: 'The Civic Type R combines race-inspired engineering with everyday practicality and exceptional handling.',
        features: ['Brembo Brakes', 'Adaptive Suspension', 'Rev Match', 'Sport Seats']
    },
    {
        id: 'subaru-wrx-sti',
        name: 'Subaru WRX STI',
        subtitle: 'Turbo Boxer · 310 hp',
        price: '$43,000',
        badge: 'Rally',
        category: 'sports',
        year: 2020,
        image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=400',
        heroImage: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=800',
        engine: '2.5L Turbo Boxer',
        horsepower: '310 hp',
        topSpeed: '160 mph',
        zeroToSixty: '4.9s',
        transmission: '6-Speed Manual',
        drivetrain: 'AWD',
        description: 'A rally legend offering symmetrical all-wheel drive, turbocharged performance, and outstanding grip.',
        features: ['SI-Drive', 'Driver Controlled Center Differential', 'Brembo Brakes', 'Sport Suspension']
    },
    {
        id: 'maserati-mc20',
        name: 'Maserati MC20',
        subtitle: 'Twin-Turbo V6 · 621 hp',
        price: '$215,000',
        badge: 'Supercar',
        category: 'supercar',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1494905998402-395d579af36f?w=400',
        heroImage: 'https://images.unsplash.com/photo-1494905998402-395d579af36f?w=800',
        engine: '3.0L Twin-Turbo V6',
        horsepower: '621 hp',
        topSpeed: '202 mph',
        zeroToSixty: '2.9s',
        transmission: '8-Speed DCT',
        drivetrain: 'RWD',
        description: 'The MC20 marks Maserati\'s return to the supercar world with lightweight construction and Italian elegance.',
        features: ['Butterfly Doors', 'Carbon Tub', 'Launch Control', 'Premium Audio']
    },
    {
        id: 'alfa-romeo-giulia-quadrifoglio',
        name: 'Alfa Romeo Giulia Quadrifoglio',
        subtitle: 'Twin-Turbo V6 · 505 hp',
        price: '$82,000',
        badge: 'Performance',
        category: 'performance',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=400',
        heroImage: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800',
        engine: '2.9L Twin-Turbo V6',
        horsepower: '505 hp',
        topSpeed: '191 mph',
        zeroToSixty: '3.8s',
        transmission: '8-Speed Automatic',
        drivetrain: 'RWD',
        description: 'A sports sedan with Ferrari-derived engineering and exhilarating performance.',
        features: ['Carbon Fiber Roof', 'Adaptive Dampers', 'Leather Interior', 'Sport Exhaust']
    },
    {
        id: 'jaguar-f-type-r',
        name: 'Jaguar F-Type R',
        subtitle: 'Supercharged V8 · 575 hp',
        price: '$112,000',
        badge: 'Luxury',
        category: 'luxury',
        year: 2022,
        image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400',
        heroImage: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
        engine: '5.0L Supercharged V8',
        horsepower: '575 hp',
        topSpeed: '186 mph',
        zeroToSixty: '3.5s',
        transmission: '8-Speed Automatic',
        drivetrain: 'AWD',
        description: 'The Jaguar F-Type R offers dramatic styling, a roaring V8 soundtrack, and outstanding grand touring capability.',
        features: ['Meridian Audio', 'Adaptive Dynamics', 'Panoramic Roof', 'Performance Seats']
    },
    {
        id: 'volvo-xc90-recharge',
        name: 'Volvo XC90 Recharge',
        subtitle: 'Hybrid · 455 hp',
        price: '$82,500',
        badge: 'Hybrid',
        category: 'suv',
        year: 2024,
        image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=400',
        heroImage: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800',
        engine: 'Plug-in Hybrid',
        horsepower: '455 hp',
        topSpeed: '112 mph',
        zeroToSixty: '5.0s',
        transmission: '8-Speed Automatic',
        drivetrain: 'AWD',
        description: 'The XC90 Recharge delivers Scandinavian luxury with advanced plug-in hybrid efficiency and safety.',
        features: ['Pilot Assist', 'Panoramic Roof', 'Air Suspension', 'Google Built-in']
    },
    {
        id: 'genesis-gv80',
        name: 'Genesis GV80',
        subtitle: 'Twin-Turbo V6 · 375 hp',
        price: '$72,000',
        badge: 'Luxury SUV',
        category: 'suv',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400',
        heroImage: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
        engine: '3.5L Twin-Turbo V6',
        horsepower: '375 hp',
        topSpeed: '149 mph',
        zeroToSixty: '5.3s',
        transmission: '8-Speed Automatic',
        drivetrain: 'AWD',
        description: 'The Genesis GV80 combines premium craftsmanship, advanced technology, and refined performance.',
        features: ['Nappa Leather', 'Lexicon Audio', 'Highway Driving Assist', 'Head-Up Display']
    },
    {
        id: 'rimac-nevera',
        name: 'Rimac Nevera',
        subtitle: 'Electric · 1914 hp',
        price: '$2,300,000',
        badge: 'Electric Hypercar',
        category: 'electric',
        year: 2023,
        image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=400',
        heroImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800',
        engine: 'Quad Electric Motors',
        horsepower: '1914 hp',
        topSpeed: '258 mph',
        zeroToSixty: '1.85s',
        transmission: 'Single-Speed',
        drivetrain: 'AWD',
        description: 'The Rimac Nevera is one of the world\'s fastest electric hypercars, combining astonishing acceleration with cutting-edge battery technology.',
        features: ['Carbon Monocoque', '120 kWh Battery', 'AI Torque Vectoring', 'Fast Charging']
    }
];